# Generated by Django 5.2.4 on 2025-07-23 14:05

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Lecture",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("start_dt", models.DateTimeField()),
                ("end_dt", models.DateTimeField()),
                ("location", models.CharField(blank=True, max_length=100)),
                (
                    "course",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="lectures",
                        to="core.course",
                    ),
                ),
            ],
            options={
                "ordering": ["start_dt"],
            },
        ),
    ]
