# Generated by Django 5.2.4 on 2025-07-27 02:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0003_alter_course_name"),
    ]

    operations = [
        migrations.AlterField(
            model_name="lecture",
            name="location",
            field=models.CharField(max_length=100),
        ),
    ]
