# Generated by Django 5.2.4 on 2025-07-28 18:10

import core.storage_backends
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0005_attendance"),
    ]

    operations = [
        migrations.AddField(
            model_name="attendance",
            name="summary",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="attendance",
            name="note_upload",
            field=models.FileField(
                blank=True,
                null=True,
                storage=core.storage_backends.NoteUploadS3Storage(),
                upload_to="",
            ),
        ),
    ]
