# Generated by Django 5.2.4 on 2025-08-18 01:17

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0006_attendance_summary_alter_attendance_note_upload"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddConstraint(
            model_name="attendance",
            constraint=models.UniqueConstraint(
                fields=("user", "lecture"), name="uniq_user_lecture_attendance"
            ),
        ),
    ]
